// Generated by tools/generate_versions.py. Do not edit.

enum GeneratedVersion {
    static let release = "1.4.5"
    static let app = "1.4.5"
    static let appBuild = 28
    static let agent = "1.4.5"
    static let agentBuild = 28
    static let agentAPIMajor = 1
    static let agentAPIMinor = 0
    static let deviceProtocolMajor = 2
    static let deviceProtocolMinor = 4
    static let capabilities = [
        "control.keys.v1",
        "audio.pcm16-16k.v1",
        "agents.snapshot.v1",
        "agents.phase.v1",
        "quota.v1",
        "wifi.enterprise.peap.v1",
        "control.voice.v1",
        "control.voice-ack.v1",
        "control.voice-enter-policy.v1",
        "control.keys-ack.v1",
        "transport.select.v1",
        "transport.ble-gatt.v1",
        "audio.ble-ima-adpcm16k.v1"
    ]
}
