#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]


def _load() -> dict[str, Any]:
    data = json.loads((ROOT / "version.json").read_text(encoding="utf-8"))
    for section in ("windows_app", "bridge_agent", "firmware"):
        value = data.get(section)
        if not isinstance(value, dict):
            raise ValueError(f"version.json {section} must be an object")
        if not isinstance(value.get("version"), str):
            raise ValueError(f"version.json {section}.version must be a string")
        if not isinstance(value.get("build"), int):
            raise ValueError(f"version.json {section}.build must be an integer")
    if data.get("release") != data["windows_app"]["version"]:
        raise ValueError("release and windows_app.version must match")
    if data["windows_app"] != data["bridge_agent"]:
        raise ValueError("windows_app and bridge_agent version/build must match")
    capabilities = data.get("capabilities")
    if not isinstance(capabilities, list) or not all(
        isinstance(item, str) and item for item in capabilities
    ):
        raise ValueError("capabilities must be a list of non-empty strings")
    return data


def _python(data: dict[str, Any]) -> str:
    capabilities = "".join(f'    "{item}",\n' for item in data["capabilities"])
    return f'''# Generated by tools/generate_versions.py. Do not edit.

RELEASE_VERSION = "{data["release"]}"
WINDOWS_APP_VERSION = "{data["windows_app"]["version"]}"
WINDOWS_APP_BUILD = {data["windows_app"]["build"]}
AGENT_VERSION = "{data["bridge_agent"]["version"]}"
AGENT_BUILD = {data["bridge_agent"]["build"]}
AGENT_API_MAJOR = {data["agent_api"]["major"]}
AGENT_API_MINOR = {data["agent_api"]["minor"]}
FIRMWARE_VERSION = "{data["firmware"]["version"]}"
MIN_FIRMWARE_VERSION = "{data["compatibility"]["min_firmware"]}"
DEVICE_PROTOCOL_MAJOR = {data["device_protocol"]["major"]}
DEVICE_PROTOCOL_MINOR = {data["device_protocol"]["minor"]}
CONFIG_SCHEMA = {data["config_schema"]}
SUPPORT_LEGACY_PROTOCOL_1 = {data["compatibility"]["legacy_protocol_1"]!r}
CAPABILITIES = (
{capabilities})
'''


def _cpp(data: dict[str, Any]) -> str:
    capabilities = "".join(
        f'    "{item}",\n' for item in data["capabilities"]
    )
    legacy = "true" if data["compatibility"]["legacy_protocol_1"] else "false"
    return f'''// Generated by tools/generate_versions.py. Do not edit.
#pragma once

#include <cstddef>
#include <cstdint>

namespace cardbridge {{

inline constexpr char kFirmwareVersion[] = "{data["firmware"]["version"]}";
inline constexpr uint32_t kFirmwareBuild = {data["firmware"]["build"]};
inline constexpr uint8_t kDeviceProtocolMajor = {data["device_protocol"]["major"]};
inline constexpr uint8_t kDeviceProtocolMinor = {data["device_protocol"]["minor"]};
inline constexpr bool kSupportLegacyProtocol1 = {legacy};
inline constexpr const char* kDeviceCapabilities[] = {{
{capabilities}}};
inline constexpr size_t kDeviceCapabilityCount =
    sizeof(kDeviceCapabilities) / sizeof(kDeviceCapabilities[0]);

}}  // namespace cardbridge
'''


def _compatibility(data: dict[str, Any]) -> str:
    output = {
        "schema": 1,
        "release": data["release"],
        "windows_app": {
            **data["windows_app"],
            "minimum_windows": "10",
            "architectures": ["x86_64"],
        },
        "bridge_agent": data["bridge_agent"],
        "firmware": data["firmware"],
        "agent_api": data["agent_api"],
        "device_protocol": data["device_protocol"],
        "minimum_firmware": data["compatibility"]["min_firmware"],
        "legacy_protocol_1": data["compatibility"]["legacy_protocol_1"],
        "capabilities": data["capabilities"],
    }
    return json.dumps(output, indent=2, ensure_ascii=False, sort_keys=True) + "\n"


def outputs(data: dict[str, Any]) -> dict[Path, str]:
    return {
        ROOT / "bridge" / "cardbridge" / "_generated_version.py": _python(data),
        ROOT / "src" / "generated_version.h": _cpp(data),
        ROOT / "release" / "compatibility.json": _compatibility(data),
    }


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate PanPal version constants")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    stale: list[Path] = []
    for path, content in outputs(_load()).items():
        if path.exists() and path.read_text(encoding="utf-8") == content:
            continue
        if args.check:
            stale.append(path.relative_to(ROOT))
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"generated {path.relative_to(ROOT)}")
    if stale:
        for path in stale:
            print(f"stale generated file: {path}")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
