# Generated by tools/generate_versions.py. Do not edit.

RELEASE_VERSION = "1.0.0"
APP_VERSION = "1.0.0"
APP_BUILD = 6
AGENT_VERSION = "1.0.0"
AGENT_BUILD = 6
AGENT_API_MAJOR = 1
AGENT_API_MINOR = 0
FIRMWARE_VERSION = "0.2.0"
MIN_FIRMWARE_VERSION = "0.1.0"
DEVICE_PROTOCOL_MAJOR = 2
DEVICE_PROTOCOL_MINOR = 0
CONFIG_SCHEMA = 2
SUPPORT_LEGACY_PROTOCOL_1 = True
CAPABILITIES = (
    "control.keys.v1",
    "audio.pcm16-16k.v1",
    "agents.snapshot.v1",
    "agents.phase.v1",
    "quota.v1",
)
