# Generated by tools/generate_versions.py. Do not edit.

RELEASE_VERSION = "1.4.5"
APP_VERSION = "1.4.5"
APP_BUILD = 28
AGENT_VERSION = "1.4.5"
AGENT_BUILD = 28
AGENT_API_MAJOR = 1
AGENT_API_MINOR = 0
FIRMWARE_VERSION = "0.6.5"
MIN_FIRMWARE_VERSION = "0.4.0"
DEVICE_PROTOCOL_MAJOR = 2
DEVICE_PROTOCOL_MINOR = 4
CONFIG_SCHEMA = 3
SUPPORT_LEGACY_PROTOCOL_1 = True
CAPABILITIES = (
    "control.keys.v1",
    "audio.pcm16-16k.v1",
    "agents.snapshot.v1",
    "agents.phase.v1",
    "quota.v1",
    "wifi.enterprise.peap.v1",
    "control.voice.v1",
    "control.voice-ack.v1",
    "control.voice-enter-policy.v1",
    "control.keys-ack.v1",
    "transport.select.v1",
    "transport.ble-gatt.v1",
    "audio.ble-ima-adpcm16k.v1",
)
