#pragma once

#include <Arduino.h>
#include <IPAddress.h>

namespace cardbridge {

struct WifiNetwork {
  String ssid;
  String password;
};

struct WifiScanResult {
  String ssid;
  int32_t rssi = -127;
  bool encrypted = true;
  bool saved = false;
};

struct PairedMac {
  String id;
  String name;
  String token;  // 64 hex chars: 32 random bytes generated by the bridge.
};

struct DiscoveredMac {
  String id;
  String name;
  IPAddress ip;
  uint16_t port = 7788;
  bool paired = false;
};

struct DeviceSettings {
  bool micMuted = false;
  uint8_t typelessFunctionKey = 13;
  uint8_t brightness = 128;
  uint16_t screenTimeoutSec = 60;
  String lastMacId;
};

enum class LinkState : uint8_t {
  Offline,
  Discovering,
  Connecting,
  AwaitingPairCode,
  Authenticating,
  Connected,
};

}  // namespace cardbridge
